import { MCPProject, MCPTool, MCPResource, MCPPrompt } from '../types/mcp';

export function generateMCPServerCode(project: MCPProject): string {
  return `#!/usr/bin/env node

/**
 * ${project.name}
 * ${project.description}
 *
 * Generated by MCP Builder
 * https://mcp-builder.vercel.app
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ListResourcesRequestSchema,
  ReadResourceRequestSchema,
  ListPromptsRequestSchema,
  GetPromptRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

// Create server instance
const server = new Server(
  {
    name: '${project.name.toLowerCase().replace(/\s+/g, '-')}',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: ${project.tools.length > 0 ? '{}' : 'undefined'},
      resources: ${project.resources.length > 0 ? '{}' : 'undefined'},
      prompts: ${project.prompts.length > 0 ? '{}' : 'undefined'},
    },
  }
);

${generateToolHandlers(project.tools)}

${generateResourceHandlers(project.resources)}

${generatePromptHandlers(project.prompts)}

// Start the server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('${project.name} MCP server running on stdio');
}

main().catch((error) => {
  console.error('Server error:', error);
  process.exit(1);
});
`;
}

function generateToolHandlers(tools: MCPTool[]): string {
  if (tools.length === 0) return '';

  return `// Tool Handlers
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
${tools.map(tool => `      {
        name: '${tool.name}',
        description: '${tool.description}',
        inputSchema: ${JSON.stringify(tool.inputSchema, null, 10).replace(/\n/g, '\n        ')},
      }`).join(',\n')}
    ],
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  switch (name) {
${tools.map(tool => generateToolCase(tool)).join('\n')}
    default:
      throw new Error(\`Unknown tool: \${name}\`);
  }
});
`;
}

function generateToolCase(tool: MCPTool): string {
  const params = Object.keys(tool.inputSchema.properties || {});
  const paramValidation = params.map(param => {
    const isRequired = tool.inputSchema.required?.includes(param);
    if (isRequired) {
      return `      if (!args.${param}) {
        throw new Error('Missing required parameter: ${param}');
      }`;
    }
    return '';
  }).filter(Boolean).join('\n');

  return `    case '${tool.name}':
${paramValidation ? paramValidation + '\n' : ''}      // TODO: Implement ${tool.name} logic
      // Available parameters: ${params.join(', ')}
      return {
        content: [
          {
            type: 'text',
            text: \`Called ${tool.name} with: \${JSON.stringify(args, null, 2)}\`,
          },
        ],
      };
`;
}

function generateResourceHandlers(resources: MCPResource[]): string {
  if (resources.length === 0) return '';

  return `// Resource Handlers
server.setRequestHandler(ListResourcesRequestSchema, async () => {
  return {
    resources: [
${resources.map(resource => `      {
        uri: '${resource.uri}',
        name: '${resource.name}',
        description: '${resource.description}',
        mimeType: '${resource.mimeType || 'text/plain'}',
      }`).join(',\n')}
    ],
  };
});

server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
  const { uri } = request.params;

  switch (uri) {
${resources.map(resource => `    case '${resource.uri}':
      // TODO: Implement resource retrieval for ${resource.name}
      return {
        contents: [
          {
            uri: '${resource.uri}',
            mimeType: '${resource.mimeType || 'text/plain'}',
            text: 'Resource data for ${resource.name}',
          },
        ],
      };
`).join('\n')}
    default:
      throw new Error(\`Unknown resource: \${uri}\`);
  }
});
`;
}

function generatePromptHandlers(prompts: MCPPrompt[]): string {
  if (prompts.length === 0) return '';

  return `// Prompt Handlers
server.setRequestHandler(ListPromptsRequestSchema, async () => {
  return {
    prompts: [
${prompts.map(prompt => {
  const args = prompt.arguments || [];
  return `      {
        name: '${prompt.name}',
        description: '${prompt.description}',${args.length > 0 ? `
        arguments: [
${args.map(arg => `          {
            name: '${arg.name}',
            description: '${arg.description}',
            required: ${arg.required || false},
          }`).join(',\n')}
        ],` : ''}
      }`;
}).join(',\n')}
    ],
  };
});

server.setRequestHandler(GetPromptRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  switch (name) {
${prompts.map(prompt => {
  const argNames = prompt.arguments?.map(a => a.name) || [];
  return `    case '${prompt.name}':
      // TODO: Implement ${prompt.name} prompt logic
      // Available arguments: ${argNames.join(', ') || 'none'}
      return {
        messages: [
          {
            role: 'user',
            content: {
              type: 'text',
              text: \`Prompt: ${prompt.description}\${args ? ' with args: ' + JSON.stringify(args) : ''}\`,
            },
          },
        ],
      };
`;
}).join('\n')}
    default:
      throw new Error(\`Unknown prompt: \${name}\`);
  }
});
`;
}

export function generatePackageJson(project: MCPProject): string {
  return JSON.stringify({
    name: project.name.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    description: project.description,
    type: 'module',
    bin: {
      [project.name.toLowerCase().replace(/\s+/g, '-')]: './build/index.js'
    },
    scripts: {
      build: 'tsc',
      prepare: 'npm run build',
      watch: 'tsc --watch'
    },
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.0.0'
    },
    devDependencies: {
      '@types/node': '^20.0.0',
      'typescript': '^5.0.0'
    }
  }, null, 2);
}

export function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'Node16',
      moduleResolution: 'Node16',
      outDir: './build',
      rootDir: './src',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true
    },
    include: ['src/**/*'],
    exclude: ['node_modules']
  }, null, 2);
}

export function generateReadme(project: MCPProject): string {
  return `# ${project.name}

${project.description}

## Installation

\`\`\`bash
npm install
\`\`\`

## Building

\`\`\`bash
npm run build
\`\`\`

## Usage

This MCP server can be used with any MCP-compatible client.

### Claude Desktop Configuration

Add this to your Claude Desktop configuration:

\`\`\`json
{
  "mcpServers": {
    "${project.name.toLowerCase().replace(/\s+/g, '-')}": {
      "command": "node",
      "args": ["/absolute/path/to/build/index.js"]
    }
  }
}
\`\`\`

## Available Primitives

### Tools (${project.tools.length})
${project.tools.map(t => `- **${t.name}**: ${t.description}`).join('\n')}

### Resources (${project.resources.length})
${project.resources.map(r => `- **${r.name}**: ${r.description} (${r.uri})`).join('\n')}

### Prompts (${project.prompts.length})
${project.prompts.map(p => `- **${p.name}**: ${p.description}`).join('\n')}

## Development

To watch for changes:

\`\`\`bash
npm run watch
\`\`\`

## Generated by MCP Builder

This server was generated by [MCP Builder](https://mcp-builder.vercel.app).
`;
}
